apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 1.1.1.1
      containers:
        - name: pihole
          image: pihole/pihole:2021.10
          imagePullPolicy: IfNotPresent
          env:
          - name: TZ
            value: "America/Los_Angeles"
          - name: WEBPASSWORD
            value: <CUSTOMIZE>
          securityContext:
            privileged: true
          ports:
          - containerPort: 53
            protocol: TCP
          - containerPort: 53
            protocol: UDP
          - containerPort: 67
            protocol: UDP
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          volumeMounts:
          - name: etc-volume
            mountPath: /etc/pihole
          - name: dnsmasq-volume
            mountPath: /etc/dnsmasq.d
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 1
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
      volumes:
        - name: etc-volume
          hostPath:
            path: /opt/pihole/etc
            type: Directory
        - name: dnsmasq-volume
          hostPath:
            path: /opt/pihole/dnsmasq
            type: Directory

